### ISSUE TITLE
Predictive performance of latent representation

### ISSUE THREAD

**Issue by vthost** [muhanzhang/D-VAE#2]
Could you please give more details about how to reproduce Table 2 in the paper?
The repository contains train commands for the models and scripts for the Bayesian optimization. But for the Table 2 experiments, it seems that SGP has to be trained differently? There is the following option in the bo.py code, but I do not find the sh file. Thank you already!

if args.predictor:
        copy('run_pred_{}.sh'.format(data_type), save_dir)

**Comment by muhanzhang** [comment]
Hi, you don't need to call the "run_pred_{}.sh". You can just do BO experiments normally following the README, and then "python summarize.py" will print the rmse and pearson's r values of each model and save them in "bayesian_optimization/**_aggregate_results/output.txt". 

The predictive performance is just gotten from the first BO iteration (i.e., use the trained sparse GP in the first iteration to evaluate on the test graphs).
